# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc2e3a5d357e6f09fcd26b074f7e6938091ba8555ff046f3339f0e02cfb58ad6e4b91253245c3abf563e847c7988c2a7904b2d83a9d195efbf4a9303bcd4a937

test:
  secret_key_base: 133c80cb71c0cc22a2c14a85d186738d47c0b43ac3a864b9b75dbf3f68a2e453a15e1ba7c49b0e742fec11a50bd50b11e979a5ed76ff2ea014cf072064512e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
